export enum PolicyResource {
    NAVIGATION_METADATA = '/orchestrator/metadata/',
    NAVIGATION_SETTINGS = '/orchestrator/settings/',
    NAVIGATION_SUBSCRIPTIONS = '/orchestrator/subscriptions/',
    NAVIGATION_TASKS = '/orchestrator/tasks/',
    NAVIGATION_WORKFLOWS = '/orchestrator/processes/',
    PROCESS_ABORT = '/orchestrator/processes/abort/',
    PROCESS_DELETE = '/orchestrator/processes/delete/',
    PROCESS_DETAILS = '/orchestrator/processes/details/',
    PROCESS_RELATED_SUBSCRIPTIONS = '/orchestrator/subscriptions/view/from-process',
    PROCESS_RETRY = '/orchestrator/processes/retry/',
    PROCESS_USER_INPUT = '/orchestrator/processes/user-input/',
    SUBSCRIPTION_CREATE = '/orchestrator/processes/create/process/menu',
    SUBSCRIPTION_MODIFY = '/orchestrator/subscriptions/modify/',
    SUBSCRIPTION_TERMINATE = '/orchestrator/subscriptions/terminate/',
    SUBSCRIPTION_VALIDATE = '/orchestrator/subscriptions/validate/',
    TASKS_CREATE = '/orchestrator/processes/create/task',
    TASKS_RETRY_ALL = '/orchestrator/processes/all-tasks/retry',
    SETTINGS_FLUSH_CACHE = '/orchestrator/settings/flush-cache',
    SETTINGS_START_STOP_ENGINE = '/orchestrator/settings/start-stop-engine',
    SET_IN_SYNC = '/orchestrator/subscriptions/set-in-sync',
}
