export const GRAPHQL_ENDPOINT_CORE = `${process.env.NEXT_PUBLIC_ORCHESTRATOR_GRAPHQL_HOST}${process.env.NEXT_PUBLIC_ORCHESTRATOR_GRAPHQL_PATH}`;

export const ORCHESTRATOR_API_BASE_URL = `${process.env.NEXT_PUBLIC_ORCHESTRATOR_API_HOST}${process.env.NEXT_PUBLIC_ORCHESTRATOR_API_PATH}`;

export const ENGINE_STATUS_ENDPOINT = `${ORCHESTRATOR_API_BASE_URL}/settings/status`;
export const PROCESS_STATUS_COUNTS_ENDPOINT = `${ORCHESTRATOR_API_BASE_URL}/processes/status-counts`;
export const SUBSCRIPTION_ACTIONS_ENDPOINT = `${ORCHESTRATOR_API_BASE_URL}/subscriptions/workflows`;
export const SUBSCRIPTION_PROCESSES_ENDPOINT = `${ORCHESTRATOR_API_BASE_URL}/processes/process-subscriptions-by-subscription-id`;

export const PROCESS_DETAIL_DEFAULT_REFETCH_INTERVAL = 3000;
