version: '3'
services:
    start-dev:
        image: quay.io/keycloak/keycloak:22.0.5
        command: start-dev
        ports:
            - '${KEYCLOAK_PORT}:8080'
        environment:
            - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
            - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
