name: Linting and Prettier check
on: [push]
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'yarn'
            - uses: actions/cache@v2
              with:
                path: '**/node_modules'
                key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            - name: Installing dependencies
              run: yarn install --frozen-lockfile

    linting-and-prettier:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'yarn'
            - uses: actions/cache@v2
              with:
                path: '**/node_modules'
                key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            - name: Installing dependencies
              run: yarn install --frozen-lockfile
            - run: yarn run tsc:example-orchestrator-ui
            - run: yarn run tsc:orchestrator-ui-components
            - run: yarn run lint:example-orchestrator-ui
            - run: yarn run lint:orchestrator-ui-components
            - run: yarn run prettier

    unit-tests:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - uses: actions/cache@v2
              with:
                path: '**/node_modules'
                key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            - name: Installing dependencies
              run: yarn install --frozen-lockfile
            - run: yarn run test:all
