name: Lint, test and build
on: [push]
jobs:
    cache-dependencies:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/package.json') }}
            - name: Installing dependencies
              run: pnpm install --frozen-lockfile

    linting-and-prettier:
        runs-on: ubuntu-latest
        needs: cache-dependencies
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/package.json') }}
            - name: Installing dependencies
              run: pnpm install --frozen-lockfile
            - run: pnpm run tsc
            - run: pnpm run lint
            - run: pnpm run prettier

    unit-tests:
        runs-on: ubuntu-latest
        needs: cache-dependencies
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/package.json') }}
            - name: Installing dependencies
              run: pnpm install --frozen-lockfile
            - run: pnpm run test

    build:
        runs-on: ubuntu-latest
        needs: cache-dependencies
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - uses: actions/cache@v4
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-node-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/package.json') }}
            - name: Installing dependencies
              run: pnpm install --frozen-lockfile
            - run: pnpm run build
