name: Linting and Prettier check
on: [push]
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: Installing dependencies
              run: yarn install --frozen-lockfile

    linting-and-prettier:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - run: yarn run tsc:example-orchestrator-ui
            - run: yarn run tsc:orchestrator-ui-components
            - run: yarn run lint:example-orchestrator-ui
            - run: yarn run lint:orchestrator-ui-components
            - run: yarn run lint:example-orchestrator-ui-e2e
            - run: yarn run prettier

    unit-tests:
        runs-on: ubuntu-latest
        needs: setup
        steps:
            - run: yarn run test:affected
